
name: React native App build

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: installing dependencies
        run: yarn install
      
      - name: prepare for android build
        run: cd android && chmod +x ./gradlew
      
      - name: build android app
        run: cd android && ./gradlew assembleRelease --no-daemon
      
      - name: release app
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release
      
